version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  mockdata:
    build: ./mockdata
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - mockdata